-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 21:21:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_test` ;

-- -----------------------------------------------------
-- Table `bd_test`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_test`.`funcionarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_test`.`tbl_remedios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_test`.`tbl_remedios` (
  `id_remedio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `validade` DATE NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `acesso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_remedio`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_test`.`registro_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_test`.`registro_vendas` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `quantidade` VARCHAR(45) NULL DEFAULT NULL,
  `metodo` VARCHAR(45) NULL DEFAULT NULL,
  `nota` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_remedio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_codigo_remedio_idx` (`codigo_remedio` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_remedio`
    FOREIGN KEY (`codigo_remedio`)
    REFERENCES `bd_test`.`tbl_remedios` (`id_remedio`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
